version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vector_view_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fred_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backups:/backups  # Optional: for database backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Performance tuning for development
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=100ms

volumes:
  postgres_data:
    driver: local

# Optional: pgAdmin for database management (uncomment if needed)
# services:
#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: vector_view_pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@vectorview.com
#       PGADMIN_DEFAULT_PASSWORD: admin123
#       PGADMIN_LISTEN_PORT: 80
#     ports:
#       - "8080:80"
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin
#     depends_on:
#       - postgres
#     restart: unless-stopped
#
# volumes:
#   pgadmin_data:
#     driver: local