#!/bin/bash
# Embedding Pipeline Cron Wrapper
# Generated by setup_embedding_pipeline_cron.sh

# Configuration
PROJECT_DIR="/home/lab/projects/vector-view"
LOG_FILE="/home/lab/projects/vector-view/ingestion/logs/embedding_pipeline_cron.log"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

# Log start
echo "$(date '+%Y-%m-%d %H:%M:%S') - Starting embedding pipeline" >> "$LOG_FILE"

# Change to semantic directory
cd "$PROJECT_DIR/semantic" || { echo "Failed to change to semantic directory" >> "$LOG_FILE"; exit 1; }

# Set PYTHONPATH to include the project root
export PYTHONPATH="$PROJECT_DIR:$PYTHONPATH"

# Run the embedding pipeline with error handling
echo "$(date '+%Y-%m-%d %H:%M:%S') - Running embedding pipeline..." >> "$LOG_FILE"
python3 embedding_pipeline.py >> "$LOG_FILE" 2>&1
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Embedding pipeline completed successfully" >> "$LOG_FILE"
else
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Embedding pipeline failed with exit code $EXIT_CODE" >> "$LOG_FILE"
fi

exit $EXIT_CODE
